/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/BaseChart.vue')['default']
    ConfirmButton: typeof import('./src/components/ConfirmButton.vue')['default']
    DynamicGreetingCard: typeof import('./src/components/DynamicGreetingCard.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    GlobalCopilotDrawer: typeof import('./src/components/GlobalCopilotDrawer.vue')['default']
    InlineError: typeof import('./src/components/InlineError.vue')['default']
    MedicalDisclaimerBanner: typeof import('./src/components/MedicalDisclaimerBanner.vue')['default']
    MedicalDisclaimerModal: typeof import('./src/components/MedicalDisclaimerModal.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonScreen: typeof import('./src/components/SkeletonScreen.vue')['default']
  }
}

// For TSX support
declare global {
  const BaseChart: typeof import('./src/components/BaseChart.vue')['default']
  const ConfirmButton: typeof import('./src/components/ConfirmButton.vue')['default']
  const DynamicGreetingCard: typeof import('./src/components/DynamicGreetingCard.vue')['default']
  const EmptyState: typeof import('./src/components/EmptyState.vue')['default']
  const ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
  const GlobalCopilotDrawer: typeof import('./src/components/GlobalCopilotDrawer.vue')['default']
  const InlineError: typeof import('./src/components/InlineError.vue')['default']
  const MedicalDisclaimerBanner: typeof import('./src/components/MedicalDisclaimerBanner.vue')['default']
  const MedicalDisclaimerModal: typeof import('./src/components/MedicalDisclaimerModal.vue')['default']
  const PageHeader: typeof import('./src/components/PageHeader.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SkeletonScreen: typeof import('./src/components/SkeletonScreen.vue')['default']
}