/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./../components/BaseChart.vue')['default']
    ConfirmButton: typeof import('./../components/ConfirmButton.vue')['default']
    DynamicGreetingCard: typeof import('./../components/DynamicGreetingCard.vue')['default']
    EmptyState: typeof import('./../components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./../components/ErrorBoundary.vue')['default']
    GlobalCopilotDrawer: typeof import('./../components/GlobalCopilotDrawer.vue')['default']
    InlineError: typeof import('./../components/InlineError.vue')['default']
    MedicalDisclaimerBanner: typeof import('./../components/MedicalDisclaimerBanner.vue')['default']
    MedicalDisclaimerModal: typeof import('./../components/MedicalDisclaimerModal.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonScreen: typeof import('./../components/SkeletonScreen.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
  }
}

// For TSX support
declare global {
  const BaseChart: typeof import('./../components/BaseChart.vue')['default']
  const ConfirmButton: typeof import('./../components/ConfirmButton.vue')['default']
  const DynamicGreetingCard: typeof import('./../components/DynamicGreetingCard.vue')['default']
  const EmptyState: typeof import('./../components/EmptyState.vue')['default']
  const ErrorBoundary: typeof import('./../components/ErrorBoundary.vue')['default']
  const GlobalCopilotDrawer: typeof import('./../components/GlobalCopilotDrawer.vue')['default']
  const InlineError: typeof import('./../components/InlineError.vue')['default']
  const MedicalDisclaimerBanner: typeof import('./../components/MedicalDisclaimerBanner.vue')['default']
  const MedicalDisclaimerModal: typeof import('./../components/MedicalDisclaimerModal.vue')['default']
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGi: typeof import('naive-ui')['NGi']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NInput: typeof import('naive-ui')['NInput']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NStatistic: typeof import('naive-ui')['NStatistic']
  const NTabPane: typeof import('naive-ui')['NTabPane']
  const NTabs: typeof import('naive-ui')['NTabs']
  const PageHeader: typeof import('./../components/PageHeader.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SkeletonScreen: typeof import('./../components/SkeletonScreen.vue')['default']
  const SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
}