/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "admin": "/admin";
    "admin_ai-feedback": "/admin/ai-feedback";
    "admin_announcement-manage": "/admin/announcement-manage";
    "admin_approval-manage": "/admin/approval-manage";
    "admin_audit-log": "/admin/audit-log";
    "admin_dashboard": "/admin/dashboard";
    "admin_exercise-manage": "/admin/exercise-manage";
    "admin_food-manage": "/admin/food-manage";
    "admin_llm-cost-monitor": "/admin/llm-cost-monitor";
    "admin_llm-ops": "/admin/llm-ops";
    "admin_notification-send": "/admin/notification-send";
    "admin_plan-feedback": "/admin/plan-feedback";
    "admin_rule-suggestion": "/admin/rule-suggestion";
    "admin_user-manage": "/admin/user-manage";
    "billing": "/billing";
    "billing_billing": "/billing/billing";
    "billing_refund-invoice": "/billing/refund-invoice";
    "body": "/body";
    "body_measurement": "/body/measurement";
    "chat": "/chat";
    "chat_chat-bot": "/chat/chat-bot";
    "checkin": "/checkin";
    "checkin_calendar": "/checkin/calendar";
    "community": "/community";
    "community_feed": "/community/feed";
    "dashboard": "/dashboard";
    "enterprise": "/enterprise";
    "enterprise_activate": "/enterprise/activate";
    "exercise": "/exercise";
    "exercise_record": "/exercise/record";
    "export": "/export";
    "export_export": "/export/export";
    "food": "/food";
    "food_record": "/food/record";
    "goal": "/goal";
    "goal_milestones": "/goal/milestones";
    "health": "/health";
    "health_blood-sugar": "/health/blood-sugar";
    "health_create": "/health/create";
    "health_form": "/health/form";
    "health_report": "/health/report";
    "health_view": "/health/view";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "notification": "/notification";
    "notification_notification-list": "/notification/notification-list";
    "plan": "/plan";
    "plan_detail": "/plan/detail";
    "plan_generate": "/plan/generate";
    "plan_list": "/plan/list";
    "settings": "/settings";
    "settings_accessibility": "/settings/accessibility";
    "settings_notification-preference": "/settings/notification-preference";
    "settings_privacy": "/settings/privacy";
    "sleep": "/sleep";
    "sleep_record": "/sleep/record";
    "statistics": "/statistics";
    "statistics_dashboard": "/statistics/dashboard";
    "water": "/water";
    "water_record": "/water/record";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "admin"
    | "billing"
    | "body"
    | "chat"
    | "checkin"
    | "community"
    | "dashboard"
    | "enterprise"
    | "exercise"
    | "export"
    | "food"
    | "goal"
    | "health"
    | "iframe-page"
    | "login"
    | "notification"
    | "plan"
    | "settings"
    | "sleep"
    | "statistics"
    | "water"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "admin_ai-feedback"
    | "admin_announcement-manage"
    | "admin_approval-manage"
    | "admin_audit-log"
    | "admin_dashboard"
    | "admin_exercise-manage"
    | "admin_food-manage"
    | "admin_llm-cost-monitor"
    | "admin_llm-ops"
    | "admin_notification-send"
    | "admin_plan-feedback"
    | "admin_rule-suggestion"
    | "admin_user-manage"
    | "billing_billing"
    | "billing_refund-invoice"
    | "body_measurement"
    | "chat_chat-bot"
    | "checkin_calendar"
    | "community_feed"
    | "dashboard"
    | "enterprise_activate"
    | "exercise_record"
    | "export_export"
    | "food_record"
    | "goal_milestones"
    | "health_blood-sugar"
    | "health_create"
    | "health_form"
    | "health_report"
    | "health_view"
    | "notification_notification-list"
    | "plan_detail"
    | "plan_generate"
    | "plan_list"
    | "settings_accessibility"
    | "settings_notification-preference"
    | "settings_privacy"
    | "sleep_record"
    | "statistics_dashboard"
    | "water_record"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
