/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "admin_ai-feedback": () => import("@/views/admin/ai-feedback/index.vue"),
  "admin_announcement-manage": () => import("@/views/admin/announcement-manage/index.vue"),
  "admin_approval-manage": () => import("@/views/admin/approval-manage/index.vue"),
  "admin_audit-log": () => import("@/views/admin/audit-log/index.vue"),
  admin_dashboard: () => import("@/views/admin/dashboard/index.vue"),
  "admin_exercise-manage": () => import("@/views/admin/exercise-manage/index.vue"),
  "admin_food-manage": () => import("@/views/admin/food-manage/index.vue"),
  "admin_llm-cost-monitor": () => import("@/views/admin/llm-cost-monitor/index.vue"),
  "admin_llm-ops": () => import("@/views/admin/llm-ops/index.vue"),
  "admin_notification-send": () => import("@/views/admin/notification-send/index.vue"),
  "admin_plan-feedback": () => import("@/views/admin/plan-feedback/index.vue"),
  "admin_rule-suggestion": () => import("@/views/admin/rule-suggestion/index.vue"),
  "admin_user-manage": () => import("@/views/admin/user-manage/index.vue"),
  billing_billing: () => import("@/views/billing/billing/index.vue"),
  "billing_refund-invoice": () => import("@/views/billing/refund-invoice/index.vue"),
  body_measurement: () => import("@/views/body/measurement/index.vue"),
  "chat_chat-bot": () => import("@/views/chat/chat-bot/index.vue"),
  checkin_calendar: () => import("@/views/checkin/calendar/index.vue"),
  community_feed: () => import("@/views/community/feed/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  enterprise_activate: () => import("@/views/enterprise/activate/index.vue"),
  exercise_record: () => import("@/views/exercise/record/index.vue"),
  export_export: () => import("@/views/export/export/index.vue"),
  food_record: () => import("@/views/food/record/index.vue"),
  goal_milestones: () => import("@/views/goal/milestones/index.vue"),
  "health_blood-sugar": () => import("@/views/health/blood-sugar/index.vue"),
  health_create: () => import("@/views/health/create/index.vue"),
  health_form: () => import("@/views/health/form/index.vue"),
  health_report: () => import("@/views/health/report/index.vue"),
  health_view: () => import("@/views/health/view/index.vue"),
  "notification_notification-list": () => import("@/views/notification/notification-list/index.vue"),
  plan_detail: () => import("@/views/plan/detail/index.vue"),
  plan_generate: () => import("@/views/plan/generate/index.vue"),
  plan_list: () => import("@/views/plan/list/index.vue"),
  "settings_notification-preference": () => import("@/views/settings/notification-preference/index.vue"),
  settings_privacy: () => import("@/views/settings/privacy/index.vue"),
  sleep_record: () => import("@/views/sleep/record/index.vue"),
  statistics_dashboard: () => import("@/views/statistics/dashboard/index.vue"),
  water_record: () => import("@/views/water/record/index.vue"),
};
